### ISSUE TITLE
[JOSS REVIEW] Contribution and authorship

### ISSUE THREAD

**Issue by finsberg** [pyomeca/biosiglive#17]
The list of authors needs clarification. Three authors are listed in the paper, but only one (or maybe two) author(s) seems to have committed to repository. The command `git shortlog --summary` yields

```
107  Amedeo
1  Pariterre
19  aceglia
72  ceglia
```

Can you please explain the contribution of the other authors?

This is related to https://github.com/openjournals/joss-reviews/issues/5091

**Comment by aceglia** [comment]
Of course. In the list you gave in the issue, the other contributor is Pariterre but he didn't contribute to this project; he is named here because he is the maintainer of the github group "pyomeca" and he had to accept the project and some first PR before giving me full access. 
There are two other authors in my article, one (Felipe Verdugo) who developed the code with me, not in terms of coding but more in developing the methods and testing the code in a real application. The other one (Mickael Begon) is my supervisor and supervised me giving advice about the code, the application or which interfaces to implement, in the whole project and still now.
